repos:
-   repo: local # este se usa cuando se tiene las libs instalads en el sistema
    hooks:
    -   id: black
        name: black
        entry: poetry run black dapp
        language: python
        types:
          - python
    -   id: isort
        name: isort
        entry: poetry run isort dapp
        language: python
        types:
          - python
    -   id: pytest
        name: pytest
        entry: poetry run pytest
        language: python
        types:
          - python
-   repo: https://gitlab.com/pycqa/flake8 # sino se puede usar la lib directamente desde el repo, sin necesidad de instalarla
    rev: 3.9.2
    hooks:
    -   id: flake8

