repos:
-   repo: local
    hooks:
    -   id: black
        name: black
        entry: poetry run black dapp
        language: python
        types:
          - python
    -   id: isort
        name: isort
        entry: poetry run isort dapp
        language: python
        types:
          - python
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8

